feat(*): improve the public API
NeuraLegion/socket_io pull request #2
Opened 2023-08-03 23:04 UTC by derevnjuk

2023-08-04 08:44 UTC, derevnjuk commented
Draft until #1 has been merged.

2023-08-07 16:01 UTC, bararchy requested changes

2023-08-07 16:01 UTC, bararchy commented on src/engine_io/engine_io.cr
> +          end
if `@incoming` will be closed by `close` method we might get a tight loop that will eat all CPU. we should handle when `@incoming.receive?` brings back `nil` and break the loop

2023-08-07 16:01 UTC, bararchy commented on src/socket_io/emitter.cr
> +    @listeners : Hash(String, Array(EventHandler)) = Hash(String, Array(EventHandler)).new
Why use an unsafe object and then sync it with mutex instead of using GenericActor shard or better yet a channel?

2023-08-07 16:29 UTC, derevnjuk commented on src/socket_io/emitter.cr
> +    @listeners : Hash(String, Array(EventHandler)) = Hash(String, Array(EventHandler)).new
Firstly, utilizing actor-based concurrency seems overkill for this particular purpose. Secondly, the "GenericActor" you are referring to has a weird design. Thirdly, it is poorly documented. Finally, using channels you won't be able to implement pub/sub properly. 

So, I would like to focus on the design, what is the aim of this PR, rather than on the early tuning.

2023-08-07 17:21 UTC, bararchy approved these changes

2023-08-07 17:23 UTC, merged